<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/15 09:25:57
?>
<?php echo form_tag('prestasi/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($prestasi, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('prestasi[id_peserta_lomba]', __($labels['prestasi{id_peserta_lomba}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('prestasi{id_peserta_lomba}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('prestasi{id_peserta_lomba}')): ?>
    <?php echo form_error('prestasi{id_peserta_lomba}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($prestasi, 'getIdPesertaLomba', array (
  'related_class' => 'PesertaLomba',
  'control_name' => 'prestasi[id_peserta_lomba]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('prestasi[prestasi]', __($labels['prestasi{prestasi}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('prestasi{prestasi}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('prestasi{prestasi}')): ?>
    <?php echo form_error('prestasi{prestasi}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($prestasi, 'getPrestasi', array (
  'size' => 80,
  'control_name' => 'prestasi[prestasi]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('prestasi[file_piagam]', __($labels['prestasi{file_piagam}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('prestasi{file_piagam}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('prestasi{file_piagam}')): ?>
    <?php echo form_error('prestasi{file_piagam}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($prestasi, 'getFilePiagam', array (
  'control_name' => 'prestasi[file_piagam]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('prestasi[filename_baru]', __($labels['prestasi{filename_baru}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('prestasi{filename_baru}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('prestasi{filename_baru}')): ?>
    <?php echo form_error('prestasi{filename_baru}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($prestasi, 'getFilenameBaru', array (
  'size' => 80,
  'control_name' => 'prestasi[filename_baru]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('prestasi[keterangan]', __($labels['prestasi{keterangan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('prestasi{keterangan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('prestasi{keterangan}')): ?>
    <?php echo form_error('prestasi{keterangan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($prestasi, 'getKeterangan', array (
  'size' => '30x3',
  'control_name' => 'prestasi[keterangan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('prestasi' => $prestasi)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($prestasi->getId()): ?>
<?php echo button_to(__('delete'), 'prestasi/delete?id='.$prestasi->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
