<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/15 09:25:58
?>
<td colspan="5">
    <?php echo $prestasi->getPesertaLomba() ?>
     - 
    <?php echo $prestasi->getPrestasi() ?>
     - 
    <?php echo get_partial('image_view', array('type' => 'list', 'prestasi' => $prestasi)) ?>
     - 
    <?php echo $prestasi->getKeterangan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'prestasi' => $prestasi)) ?>
     - 
</td>