<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/15 09:25:58
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'prestasi/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
