<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 08:20:16
?>
    <td><?php echo link_to($prestasi->getId() ? $prestasi->getId() : __('-'), 'prestasi/edit?id='.$prestasi->getId()) ?></td>
    <td><?php echo $prestasi->getIdPesertaLomba() ?></td>
      <td><?php echo $prestasi->getPrestasi() ?></td>
      <td><?php echo $prestasi->getFilePiagam() ?></td>
      <td><?php echo $prestasi->getFilenameBaru() ?></td>
      <td><?php echo $prestasi->getKeterangan() ?></td>
      <td><?php echo ($prestasi->getCreatedAt() !== null && $prestasi->getCreatedAt() !== '') ? format_date($prestasi->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($prestasi->getUpdatedAt() !== null && $prestasi->getUpdatedAt() !== '') ? format_date($prestasi->getUpdatedAt(), "f") : '' ?></td>
      <td><?php echo $prestasi->getIsDeleted() ?></td>
  