<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/15 09:25:58
?>
    <td><?php echo $prestasi->getPesertaLomba() ?></td>
      <td><?php echo $prestasi->getPrestasi() ?></td>
      <td><?php echo get_partial('image_view', array('type' => 'list', 'prestasi' => $prestasi)) ?></td>
      <td><?php echo $prestasi->getKeterangan() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'prestasi' => $prestasi)) ?></td>
  