<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 08:20:16
?>
<td colspan="9">
    <?php echo link_to($prestasi->getId() ? $prestasi->getId() : __('-'), 'prestasi/edit?id='.$prestasi->getId()) ?>
     - 
    <?php echo $prestasi->getIdPesertaLomba() ?>
     - 
    <?php echo $prestasi->getPrestasi() ?>
     - 
    <?php echo $prestasi->getFilePiagam() ?>
     - 
    <?php echo $prestasi->getFilenameBaru() ?>
     - 
    <?php echo $prestasi->getKeterangan() ?>
     - 
    <?php echo ($prestasi->getCreatedAt() !== null && $prestasi->getCreatedAt() !== '') ? format_date($prestasi->getCreatedAt(), "f") : '' ?>
     - 
    <?php echo ($prestasi->getUpdatedAt() !== null && $prestasi->getUpdatedAt() !== '') ? format_date($prestasi->getUpdatedAt(), "f") : '' ?>
     - 
    <?php echo $prestasi->getIsDeleted() ?>
     - 
</td>