<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 08:20:15
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('edit prestasi', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('prestasi/edit_header', array('prestasi' => $prestasi)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('prestasi/edit_messages', array('prestasi' => $prestasi, 'labels' => $labels)) ?>
<?php include_partial('prestasi/edit_form', array('prestasi' => $prestasi, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('prestasi/edit_footer', array('prestasi' => $prestasi)) ?>
</div>

</div>
