<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:03:48
?>
<?php echo form_tag('pengguna/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($pengguna, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('pengguna[id_wilayah]', __($labels['pengguna{id_wilayah}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{id_wilayah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{id_wilayah}')): ?>
    <?php echo form_error('pengguna{id_wilayah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($pengguna, 'getIdWilayah', array (
  'related_class' => 'Wilayah',
  'control_name' => 'pengguna[id_wilayah]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[id_sfguarduser]', __($labels['pengguna{id_sfguarduser}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{id_sfguarduser}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{id_sfguarduser}')): ?>
    <?php echo form_error('pengguna{id_sfguarduser}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($pengguna, 'getIdSfguarduser', array (
  'related_class' => 'sfGuardUser',
  'control_name' => 'pengguna[id_sfguarduser]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[nama]', __($labels['pengguna{nama}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{nama}')): ?>
    <?php echo form_error('pengguna{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getNama', array (
  'size' => 80,
  'control_name' => 'pengguna[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[no_telp]', __($labels['pengguna{no_telp}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{no_telp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{no_telp}')): ?>
    <?php echo form_error('pengguna{no_telp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getNoTelp', array (
  'size' => 20,
  'control_name' => 'pengguna[no_telp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[file_foto]', __($labels['pengguna{file_foto}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{file_foto}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{file_foto}')): ?>
    <?php echo form_error('pengguna{file_foto}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getFileFoto', array (
  'size' => 80,
  'control_name' => 'pengguna[file_foto]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[filename_baru]', __($labels['pengguna{filename_baru}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{filename_baru}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{filename_baru}')): ?>
    <?php echo form_error('pengguna{filename_baru}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getFilenameBaru', array (
  'size' => 80,
  'control_name' => 'pengguna[filename_baru]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[keterangan]', __($labels['pengguna{keterangan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{keterangan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{keterangan}')): ?>
    <?php echo form_error('pengguna{keterangan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($pengguna, 'getKeterangan', array (
  'size' => '30x3',
  'control_name' => 'pengguna[keterangan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[created_at]', __($labels['pengguna{created_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{created_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{created_at}')): ?>
    <?php echo form_error('pengguna{created_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($pengguna, 'getCreatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'pengguna[created_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[updated_at]', __($labels['pengguna{updated_at}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{updated_at}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{updated_at}')): ?>
    <?php echo form_error('pengguna{updated_at}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($pengguna, 'getUpdatedAt', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'pengguna[updated_at]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('pengguna[is_deleted]', __($labels['pengguna{is_deleted}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('pengguna{is_deleted}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('pengguna{is_deleted}')): ?>
    <?php echo form_error('pengguna{is_deleted}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($pengguna, 'getIsDeleted', array (
  'size' => 7,
  'control_name' => 'pengguna[is_deleted]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('pengguna' => $pengguna)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($pengguna->getId()): ?>
<?php echo button_to(__('delete'), 'pengguna/delete?id='.$pengguna->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
