<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:03:49
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'pengguna/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'pengguna/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_id_wilayah">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'id_wilayah'): ?>
      <?php echo link_to(__('Id wilayah'), 'pengguna/list?sort=id_wilayah&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id wilayah'), 'pengguna/list?sort=id_wilayah&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_id_sfguarduser">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'id_sfguarduser'): ?>
      <?php echo link_to(__('Id sfguarduser'), 'pengguna/list?sort=id_sfguarduser&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id sfguarduser'), 'pengguna/list?sort=id_sfguarduser&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'pengguna/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'pengguna/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_no_telp">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'no_telp'): ?>
      <?php echo link_to(__('No telp'), 'pengguna/list?sort=no_telp&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('No telp'), 'pengguna/list?sort=no_telp&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_file_foto">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'file_foto'): ?>
      <?php echo link_to(__('File foto'), 'pengguna/list?sort=file_foto&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('File foto'), 'pengguna/list?sort=file_foto&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_filename_baru">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'filename_baru'): ?>
      <?php echo link_to(__('Filename baru'), 'pengguna/list?sort=filename_baru&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Filename baru'), 'pengguna/list?sort=filename_baru&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_keterangan">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'keterangan'): ?>
      <?php echo link_to(__('Keterangan'), 'pengguna/list?sort=keterangan&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Keterangan'), 'pengguna/list?sort=keterangan&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'created_at'): ?>
      <?php echo link_to(__('Created at'), 'pengguna/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Created at'), 'pengguna/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Updated at'), 'pengguna/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Updated at'), 'pengguna/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_is_deleted">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/pengguna/sort') == 'is_deleted'): ?>
      <?php echo link_to(__('Is deleted'), 'pengguna/list?sort=is_deleted&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/pengguna/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Is deleted'), 'pengguna/list?sort=is_deleted&type=asc') ?>
      <?php endif; ?>
          </th>
