<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:03:48
?>
<td colspan="11">
    <?php echo link_to($pengguna->getId() ? $pengguna->getId() : __('-'), 'pengguna/edit?id='.$pengguna->getId()) ?>
     - 
    <?php echo $pengguna->getIdWilayah() ?>
     - 
    <?php echo $pengguna->getIdSfguarduser() ?>
     - 
    <?php echo $pengguna->getNama() ?>
     - 
    <?php echo $pengguna->getNoTelp() ?>
     - 
    <?php echo $pengguna->getFileFoto() ?>
     - 
    <?php echo $pengguna->getFilenameBaru() ?>
     - 
    <?php echo $pengguna->getKeterangan() ?>
     - 
    <?php echo ($pengguna->getCreatedAt() !== null && $pengguna->getCreatedAt() !== '') ? format_date($pengguna->getCreatedAt(), "f") : '' ?>
     - 
    <?php echo ($pengguna->getUpdatedAt() !== null && $pengguna->getUpdatedAt() !== '') ? format_date($pengguna->getUpdatedAt(), "f") : '' ?>
     - 
    <?php echo $pengguna->getIsDeleted() ?>
     - 
</td>