<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:03:49
?>
    <td><?php echo link_to($pengguna->getId() ? $pengguna->getId() : __('-'), 'pengguna/edit?id='.$pengguna->getId()) ?></td>
    <td><?php echo $pengguna->getIdWilayah() ?></td>
      <td><?php echo $pengguna->getIdSfguarduser() ?></td>
      <td><?php echo $pengguna->getNama() ?></td>
      <td><?php echo $pengguna->getNoTelp() ?></td>
      <td><?php echo $pengguna->getFileFoto() ?></td>
      <td><?php echo $pengguna->getFilenameBaru() ?></td>
      <td><?php echo $pengguna->getKeterangan() ?></td>
      <td><?php echo ($pengguna->getCreatedAt() !== null && $pengguna->getCreatedAt() !== '') ? format_date($pengguna->getCreatedAt(), "f") : '' ?></td>
      <td><?php echo ($pengguna->getUpdatedAt() !== null && $pengguna->getUpdatedAt() !== '') ? format_date($pengguna->getUpdatedAt(), "f") : '' ?></td>
      <td><?php echo $pengguna->getIsDeleted() ?></td>
  