<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2018/03/06 13:43:12

$database = new sfPropelDatabase();
$database->initialize(array (
  'dsn' => 'mysql://root@localhost/mds_sgc',
), 'propel');
$this->databases['propel'] = $database;
