<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/28 07:35:46
?>

<?php 
$fileDir = '/uploads/Lomba/Anggota/'.$anggota_lomba->getFilenameBaru().'.png';
?>

<?php echo link_to(image_tag($fileDir, array('style'=>'max-height:150px')), 'anggotaLomba/downloadRequest?id='.$anggota_lomba->getId())?>

