<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/28 07:35:46
?>
  
<?php echo image_tag('/uploads/Lomba/Anggota/'.$anggota_lomba->getFilenameBaru().'.png', array('style'=>'max-height:150px; max-width:150px')) ?>
