<?php
// auto-generated by sfPropelAdmin
// date: 2018/01/23 11:14:21
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('Tambah Data'), 'sfGuardUser/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
