<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:45
?>
<?php echo form_tag('peserta/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($peserta, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('peserta[id_wilayah]', __($labels['peserta{id_wilayah}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta{id_wilayah}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta{id_wilayah}')): ?>
    <?php echo form_error('peserta{id_wilayah}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($peserta, 'getIdWilayah', array (
  'related_class' => 'Wilayah',
  'control_name' => 'peserta[id_wilayah]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta[rt]', __($labels['peserta{rt}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta{rt}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta{rt}')): ?>
    <?php echo form_error('peserta{rt}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta, 'getRt', array (
  'size' => 20,
  'control_name' => 'peserta[rt]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta[rw]', __($labels['peserta{rw}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta{rw}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta{rw}')): ?>
    <?php echo form_error('peserta{rw}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta, 'getRw', array (
  'size' => 20,
  'control_name' => 'peserta[rw]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta[ketua_rt]', __($labels['peserta{ketua_rt}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('peserta{ketua_rt}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta{ketua_rt}')): ?>
    <?php echo form_error('peserta{ketua_rt}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta, 'getKetuaRt', array (
  'size' => 80,
  'control_name' => 'peserta[ketua_rt]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta[ketua_rw]', __($labels['peserta{ketua_rw}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('peserta{ketua_rw}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta{ketua_rw}')): ?>
    <?php echo form_error('peserta{ketua_rw}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta, 'getKetuaRw', array (
  'size' => 80,
  'control_name' => 'peserta[ketua_rw]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('peserta' => $peserta)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($peserta->getId()): ?>
<?php echo button_to(__('delete'), 'peserta/delete?id='.$peserta->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
