<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:45
?>
    <td><?php echo $peserta->getWilayah() ?></td>
      <td><?php echo $peserta->getRt() ?></td>
      <td><?php echo $peserta->getRw() ?></td>
      <td><?php echo $peserta->getKetuaRt() ?></td>
      <td><?php echo $peserta->getKetuaRw() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'peserta' => $peserta)) ?></td>
  