<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:45
?>
<td colspan="6">
    <?php echo $peserta->getWilayah() ?>
     - 
    <?php echo $peserta->getRt() ?>
     - 
    <?php echo $peserta->getRw() ?>
     - 
    <?php echo $peserta->getKetuaRt() ?>
     - 
    <?php echo $peserta->getKetuaRw() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'peserta' => $peserta)) ?>
     - 
</td>