<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:44
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Form Pengisian Data RT/RW', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('peserta/edit_header', array('peserta' => $peserta)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('peserta/edit_messages', array('peserta' => $peserta, 'labels' => $labels)) ?>
<?php include_partial('peserta/edit_form', array('peserta' => $peserta, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('peserta/edit_footer', array('peserta' => $peserta)) ?>
</div>

</div>
