<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:39:15
?>
<?php echo form_tag('dataLomba/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($data_lomba, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('data_lomba[id_peserta_lomba]', __($labels['data_lomba{id_peserta_lomba}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('data_lomba{id_peserta_lomba}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('data_lomba{id_peserta_lomba}')): ?>
    <?php echo form_error('data_lomba{id_peserta_lomba}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($data_lomba, 'getIdPesertaLomba', array (
  'related_class' => 'PesertaLomba',
  'control_name' => 'data_lomba[id_peserta_lomba]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('data_lomba[file_foto_peserta]', __($labels['data_lomba{file_foto_peserta}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('data_lomba{file_foto_peserta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('data_lomba{file_foto_peserta}')): ?>
    <?php echo form_error('data_lomba{file_foto_peserta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($data_lomba, 'getFileFotoPeserta', array (
  'control_name' => 'data_lomba[file_foto_peserta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('data_lomba[filename_baru]', __($labels['data_lomba{filename_baru}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('data_lomba{filename_baru}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('data_lomba{filename_baru}')): ?>
    <?php echo form_error('data_lomba{filename_baru}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($data_lomba, 'getFilenameBaru', array (
  'size' => 80,
  'control_name' => 'data_lomba[filename_baru]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('data_lomba[keterangan]', __($labels['data_lomba{keterangan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('data_lomba{keterangan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('data_lomba{keterangan}')): ?>
    <?php echo form_error('data_lomba{keterangan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($data_lomba, 'getKeterangan', array (
  'size' => '30x3',
  'control_name' => 'data_lomba[keterangan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('data_lomba' => $data_lomba)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($data_lomba->getId()): ?>
<?php echo button_to(__('delete'), 'dataLomba/delete?id='.$data_lomba->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
