<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:39:15
?>
    <td><?php echo $data_lomba->getPesertaLomba() ?></td>
      <td><?php echo get_partial('image_view', array('type' => 'list', 'data_lomba' => $data_lomba)) ?></td>
      <td><?php echo $data_lomba->getKeterangan() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'data_lomba' => $data_lomba)) ?></td>
  