<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:39:15
?>
  <th id="sf_admin_list_th_peserta_lomba">
        <?php echo __('Nama Tim') ?>
          </th>
  <th id="sf_admin_list_th_image_view">
        <?php echo __('Foto Profil Wilayah') ?>
          </th>
  <th id="sf_admin_list_th_keterangan">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/data_lomba/sort') == 'keterangan'): ?>
      <?php echo link_to(__('Keterangan'), 'dataLomba/list?sort=keterangan&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/data_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/data_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Keterangan'), 'dataLomba/list?sort=keterangan&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_opsi">
        <?php echo __('Opsi') ?>
          </th>
