<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:39:14
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Form Pengisian Data Profil Wilayah', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('dataLomba/edit_header', array('data_lomba' => $data_lomba)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('dataLomba/edit_messages', array('data_lomba' => $data_lomba, 'labels' => $labels)) ?>
<?php include_partial('dataLomba/edit_form', array('data_lomba' => $data_lomba, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('dataLomba/edit_footer', array('data_lomba' => $data_lomba)) ?>
</div>

</div>
