<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 10:16:39
?>
<?php

/**
 * autoLomba actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage autoLomba
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id: actions.class.php 9855 2008-06-25 11:26:01Z FabianLange $
 */
class autoLombaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('lomba', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();


    // pager
    $this->pager = new sfPropelPager('Lomba', 20);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', $this->getUser()->getAttribute('page', 1, 'sf_admin/lomba')));
    $this->pager->init();
    // save page
    if ($this->getRequestParameter('page')) {
        $this->getUser()->setAttribute('page', $this->getRequestParameter('page'), 'sf_admin/lomba');
    }
  }

  public function executeCreate()
  {
    return $this->forward('lomba', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('lomba', 'edit');
  }

  public function executeEdit()
  {
    $this->lomba = $this->getLombaOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updateLombaFromRequest();

      $this->saveLomba($this->lomba);

      $this->setFlash('notice', 'Your modifications have been saved');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('lomba/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('lomba/list');
      }
      else
      {
        return $this->redirect('lomba/edit?id='.$this->lomba->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->lomba = LombaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->lomba);

    try
    {
      $this->deleteLomba($this->lomba);
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'Could not delete the selected Lomba. Make sure it does not have any associated items.');
      return $this->forward('lomba', 'list');
    }

    return $this->redirect('lomba/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->lomba = $this->getLombaOrCreate();
    $this->updateLombaFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function saveLomba($lomba)
  {
    $lomba->save();

  }

  protected function deleteLomba($lomba)
  {
    $lomba->delete();
  }

  protected function updateLombaFromRequest()
  {
    $lomba = $this->getRequestParameter('lomba');

    if (isset($lomba['nama']))
    {
      $this->lomba->setNama($lomba['nama']);
    }
    if (isset($lomba['tingkat']))
    {
      $this->lomba->setTingkat($lomba['tingkat']);
    }
    if (isset($lomba['kategori']))
    {
      $this->lomba->setKategori($lomba['kategori']);
    }
    if (isset($lomba['deskripsi']))
    {
      $this->lomba->setDeskripsi($lomba['deskripsi']);
    }
    if (isset($lomba['created_at']))
    {
      if ($lomba['created_at'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($lomba['created_at']))
          {
            $value = $dateFormat->format($lomba['created_at'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $lomba['created_at'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->lomba->setCreatedAt($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->lomba->setCreatedAt(null);
      }
    }
    if (isset($lomba['updated_at']))
    {
      if ($lomba['updated_at'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($lomba['updated_at']))
          {
            $value = $dateFormat->format($lomba['updated_at'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $lomba['updated_at'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->lomba->setUpdatedAt($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->lomba->setUpdatedAt(null);
      }
    }
    if (isset($lomba['is_deleted']))
    {
      $this->lomba->setIsDeleted($lomba['is_deleted']);
    }
  }

  protected function getLombaOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $lomba = new Lomba();
    }
    else
    {
      $lomba = LombaPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($lomba);
    }

    return $lomba;
  }

  protected function processFilters()
  {
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/lomba/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/lomba/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/lomba/sort'))
    {
    }
  }

  protected function addFiltersCriteria($c)
  {
  }

  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/lomba/sort'))
    {
      $sort_column = LombaPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/lomba/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'lomba{id}' => 'Id:',
      'lomba{nama}' => 'Nama:',
      'lomba{tingkat}' => 'Tingkat:',
      'lomba{kategori}' => 'Kategori:',
      'lomba{deskripsi}' => 'Deskripsi:',
      'lomba{created_at}' => 'Created at:',
      'lomba{updated_at}' => 'Updated at:',
      'lomba{is_deleted}' => 'Is deleted:',
    );
  }
}
