<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:13:36
?>
<td colspan="5">
    <?php echo $lomba->getNama() ?>
     - 
    <?php echo $lomba->getTingkat() ?>
     - 
    <?php echo $lomba->getKategori() ?>
     - 
    <?php echo $lomba->getDeskripsi() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'lomba' => $lomba)) ?>
     - 
</td>