<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:13:36
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'lomba/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
