<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 10:16:40
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'lomba/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
