<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 10:16:41
?>
  <th id="sf_admin_list_th_id">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'id'): ?>
      <?php echo link_to(__('Id'), 'lomba/list?sort=id&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Id'), 'lomba/list?sort=id&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'lomba/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'lomba/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_tingkat">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'tingkat'): ?>
      <?php echo link_to(__('Tingkat'), 'lomba/list?sort=tingkat&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Tingkat'), 'lomba/list?sort=tingkat&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_kategori">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'kategori'): ?>
      <?php echo link_to(__('Kategori'), 'lomba/list?sort=kategori&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Kategori'), 'lomba/list?sort=kategori&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_deskripsi">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'deskripsi'): ?>
      <?php echo link_to(__('Deskripsi'), 'lomba/list?sort=deskripsi&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Deskripsi'), 'lomba/list?sort=deskripsi&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_created_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'created_at'): ?>
      <?php echo link_to(__('Created at'), 'lomba/list?sort=created_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Created at'), 'lomba/list?sort=created_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_updated_at">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'updated_at'): ?>
      <?php echo link_to(__('Updated at'), 'lomba/list?sort=updated_at&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Updated at'), 'lomba/list?sort=updated_at&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_is_deleted">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/lomba/sort') == 'is_deleted'): ?>
      <?php echo link_to(__('Is deleted'), 'lomba/list?sort=is_deleted&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Is deleted'), 'lomba/list?sort=is_deleted&type=asc') ?>
      <?php endif; ?>
          </th>
