<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/20 10:13:36
?>
    <td><?php echo $lomba->getNama() ?></td>
      <td><?php echo $lomba->getTingkat() ?></td>
      <td><?php echo $lomba->getKategori() ?></td>
      <td><?php echo $lomba->getDeskripsi() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'lomba' => $lomba)) ?></td>
  