<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 10:16:40
?>
<td colspan="8">
    <?php echo link_to($lomba->getId() ? $lomba->getId() : __('-'), 'lomba/edit?id='.$lomba->getId()) ?>
     - 
    <?php echo $lomba->getNama() ?>
     - 
    <?php echo $lomba->getTingkat() ?>
     - 
    <?php echo $lomba->getKategori() ?>
     - 
    <?php echo $lomba->getDeskripsi() ?>
     - 
    <?php echo ($lomba->getCreatedAt() !== null && $lomba->getCreatedAt() !== '') ? format_date($lomba->getCreatedAt(), "f") : '' ?>
     - 
    <?php echo ($lomba->getUpdatedAt() !== null && $lomba->getUpdatedAt() !== '') ? format_date($lomba->getUpdatedAt(), "f") : '' ?>
     - 
    <?php echo $lomba->getIsDeleted() ?>
     - 
</td>