<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2018/03/14 09:22:31
sfConfig::add(array(
  'mod_'.strtolower($moduleName).'_enabled' => true,
  'mod_'.strtolower($moduleName).'_view_class' => 'sfPHP',
  'mod_'.strtolower($moduleName).'_is_internal' => false,
));
