<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 12:38:32
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'anggotaLomba/list?id='.$anggota_lomba->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('save and add'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
</ul>
