<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:06:03
?>
<?php echo form_tag('anggotaLomba/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($anggota_lomba, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('anggota_lomba[id_peserta_lomba]', __($labels['anggota_lomba{id_peserta_lomba}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{id_peserta_lomba}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{id_peserta_lomba}')): ?>
    <?php echo form_error('anggota_lomba{id_peserta_lomba}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($anggota_lomba, 'getIdPesertaLomba', array (
  'related_class' => 'PesertaLomba',
  'control_name' => 'anggota_lomba[id_peserta_lomba]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[nama]', __($labels['anggota_lomba{nama}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{nama}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{nama}')): ?>
    <?php echo form_error('anggota_lomba{nama}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($anggota_lomba, 'getNama', array (
  'size' => 80,
  'control_name' => 'anggota_lomba[nama]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[usia]', __($labels['anggota_lomba{usia}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{usia}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{usia}')): ?>
    <?php echo form_error('anggota_lomba{usia}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($anggota_lomba, 'getUsia', array (
  'size' => 7,
  'control_name' => 'anggota_lomba[usia]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[alamat]', __($labels['anggota_lomba{alamat}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{alamat}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{alamat}')): ?>
    <?php echo form_error('anggota_lomba{alamat}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($anggota_lomba, 'getAlamat', array (
  'size' => 80,
  'control_name' => 'anggota_lomba[alamat]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[no_telp]', __($labels['anggota_lomba{no_telp}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{no_telp}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{no_telp}')): ?>
    <?php echo form_error('anggota_lomba{no_telp}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($anggota_lomba, 'getNoTelp', array (
  'size' => 20,
  'control_name' => 'anggota_lomba[no_telp]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[file_foto]', __($labels['anggota_lomba{file_foto}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{file_foto}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{file_foto}')): ?>
    <?php echo form_error('anggota_lomba{file_foto}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_admin_input_file_tag($anggota_lomba, 'getFileFoto', array (
  'control_name' => 'anggota_lomba[file_foto]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('anggota_lomba[filename_baru]', __($labels['anggota_lomba{filename_baru}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('anggota_lomba{filename_baru}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('anggota_lomba{filename_baru}')): ?>
    <?php echo form_error('anggota_lomba{filename_baru}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($anggota_lomba, 'getFilenameBaru', array (
  'size' => 80,
  'control_name' => 'anggota_lomba[filename_baru]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('anggota_lomba' => $anggota_lomba)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($anggota_lomba->getId()): ?>
<?php echo button_to(__('delete'), 'anggotaLomba/delete?id='.$anggota_lomba->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
