<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:06:04
?>
    <td><?php echo $anggota_lomba->getPesertaLomba() ?></td>
      <td><?php echo $anggota_lomba->getNama() ?></td>
      <td><?php echo $anggota_lomba->getUsia() ?></td>
      <td><?php echo $anggota_lomba->getAlamat() ?></td>
      <td><?php echo $anggota_lomba->getNoTelp() ?></td>
      <td><?php echo get_partial('image_view', array('type' => 'list', 'anggota_lomba' => $anggota_lomba)) ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'anggota_lomba' => $anggota_lomba)) ?></td>
  