<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 12:38:33
?>
  <th id="sf_admin_list_th_peserta_lomba">
        <?php echo __('Peserta lomba') ?>
          </th>
  <th id="sf_admin_list_th_nama">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/anggota_lomba/sort') == 'nama'): ?>
      <?php echo link_to(__('Nama'), 'anggotaLomba/list?sort=nama&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Nama'), 'anggotaLomba/list?sort=nama&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_usia">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/anggota_lomba/sort') == 'usia'): ?>
      <?php echo link_to(__('Usia'), 'anggotaLomba/list?sort=usia&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Usia'), 'anggotaLomba/list?sort=usia&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_alamat">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/anggota_lomba/sort') == 'alamat'): ?>
      <?php echo link_to(__('Alamat'), 'anggotaLomba/list?sort=alamat&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Alamat'), 'anggotaLomba/list?sort=alamat&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_no_telp">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/anggota_lomba/sort') == 'no_telp'): ?>
      <?php echo link_to(__('No telp'), 'anggotaLomba/list?sort=no_telp&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('No telp'), 'anggotaLomba/list?sort=no_telp&type=asc') ?>
      <?php endif; ?>
          </th>
  <th id="sf_admin_list_th_image_view">
        <?php echo __('Image view') ?>
          </th>
  <th id="sf_admin_list_th_filename_baru">
          <?php if ($sf_user->getAttribute('sort', null, 'sf_admin/anggota_lomba/sort') == 'filename_baru'): ?>
      <?php echo link_to(__('Filename baru'), 'anggotaLomba/list?sort=filename_baru&type='.($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort') == 'asc' ? 'desc' : 'asc')) ?>
      (<?php echo __($sf_user->getAttribute('type', 'asc', 'sf_admin/anggota_lomba/sort')) ?>)
      <?php else: ?>
      <?php echo link_to(__('Filename baru'), 'anggotaLomba/list?sort=filename_baru&type=asc') ?>
      <?php endif; ?>
          </th>
