<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/01 12:38:33
?>
<td colspan="7">
    <?php echo $anggota_lomba->getPesertaLomba() ?>
     - 
    <?php echo $anggota_lomba->getNama() ?>
     - 
    <?php echo $anggota_lomba->getUsia() ?>
     - 
    <?php echo $anggota_lomba->getAlamat() ?>
     - 
    <?php echo $anggota_lomba->getNoTelp() ?>
     - 
    <?php echo get_partial('image_view', array('type' => 'list', 'anggota_lomba' => $anggota_lomba)) ?>
     - 
    <?php echo $anggota_lomba->getFilenameBaru() ?>
     - 
</td>