<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:06:03
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Form Pengisian Data Anggota', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('anggotaLomba/edit_header', array('anggota_lomba' => $anggota_lomba)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('anggotaLomba/edit_messages', array('anggota_lomba' => $anggota_lomba, 'labels' => $labels)) ?>
<?php include_partial('anggotaLomba/edit_form', array('anggota_lomba' => $anggota_lomba, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('anggotaLomba/edit_footer', array('anggota_lomba' => $anggota_lomba)) ?>
</div>

</div>
