<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:53
?>
<?php echo form_tag('pesertaLomba/save', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($peserta_lomba, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('peserta_lomba[id_peserta]', __($labels['peserta_lomba{id_peserta}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{id_peserta}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{id_peserta}')): ?>
    <?php echo form_error('peserta_lomba{id_peserta}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($peserta_lomba, 'getIdPeserta', array (
  'related_class' => 'Peserta',
  'control_name' => 'peserta_lomba[id_peserta]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[id_lomba]', __($labels['peserta_lomba{id_lomba}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{id_lomba}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{id_lomba}')): ?>
    <?php echo form_error('peserta_lomba{id_lomba}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($peserta_lomba, 'getIdLomba', array (
  'related_class' => 'Lomba',
  'control_name' => 'peserta_lomba[id_lomba]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[tahun]', __($labels['peserta_lomba{tahun}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{tahun}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{tahun}')): ?>
    <?php echo form_error('peserta_lomba{tahun}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta_lomba, 'getTahun', array (
  'size' => 7,
  'control_name' => 'peserta_lomba[tahun]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[nama_tim]', __($labels['peserta_lomba{nama_tim}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{nama_tim}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{nama_tim}')): ?>
    <?php echo form_error('peserta_lomba{nama_tim}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta_lomba, 'getNamaTim', array (
  'size' => 80,
  'control_name' => 'peserta_lomba[nama_tim]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[nama_penggerak_lingkungan]', __($labels['peserta_lomba{nama_penggerak_lingkungan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{nama_penggerak_lingkungan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{nama_penggerak_lingkungan}')): ?>
    <?php echo form_error('peserta_lomba{nama_penggerak_lingkungan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_tag($peserta_lomba, 'getNamaPenggerakLingkungan', array (
  'size' => 80,
  'control_name' => 'peserta_lomba[nama_penggerak_lingkungan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[tanggal_pendaftaran]', __($labels['peserta_lomba{tanggal_pendaftaran}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{tanggal_pendaftaran}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{tanggal_pendaftaran}')): ?>
    <?php echo form_error('peserta_lomba{tanggal_pendaftaran}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_input_date_tag($peserta_lomba, 'getTanggalPendaftaran', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => '/sf/sf_admin/images/date.png',
  'control_name' => 'peserta_lomba[tanggal_pendaftaran]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[program_kerja]', __($labels['peserta_lomba{program_kerja}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{program_kerja}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{program_kerja}')): ?>
    <?php echo form_error('peserta_lomba{program_kerja}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($peserta_lomba, 'getProgramKerja', array (
  'size' => '30x3',
  'control_name' => 'peserta_lomba[program_kerja]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('peserta_lomba[catatan]', __($labels['peserta_lomba{catatan}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('peserta_lomba{catatan}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('peserta_lomba{catatan}')): ?>
    <?php echo form_error('peserta_lomba{catatan}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_textarea_tag($peserta_lomba, 'getCatatan', array (
  'size' => '30x3',
  'control_name' => 'peserta_lomba[catatan]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>

<?php include_partial('edit_actions', array('peserta_lomba' => $peserta_lomba)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($peserta_lomba->getId()): ?>
<?php echo button_to(__('delete'), 'pesertaLomba/delete?id='.$peserta_lomba->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
