<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:54
?>
<td colspan="9">
    <?php echo $peserta_lomba->getNamaTim() ?>
     - 
    <?php echo $peserta_lomba->getPeserta() ?>
     - 
    <?php echo $peserta_lomba->getLomba() ?>
     - 
    <?php echo $peserta_lomba->getTahun() ?>
     - 
    <?php echo $peserta_lomba->getNamaPenggerakLingkungan() ?>
     - 
    <?php echo ($peserta_lomba->getTanggalPendaftaran() !== null && $peserta_lomba->getTanggalPendaftaran() !== '') ? format_date($peserta_lomba->getTanggalPendaftaran(), "f") : '' ?>
     - 
    <?php echo $peserta_lomba->getProgramKerja() ?>
     - 
    <?php echo $peserta_lomba->getCatatan() ?>
     - 
    <?php echo get_partial('opsi', array('type' => 'list', 'peserta_lomba' => $peserta_lomba)) ?>
     - 
</td>