<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:54
?>
    <td><?php echo $peserta_lomba->getNamaTim() ?></td>
      <td><?php echo $peserta_lomba->getPeserta() ?></td>
      <td><?php echo $peserta_lomba->getLomba() ?></td>
      <td><?php echo $peserta_lomba->getTahun() ?></td>
      <td><?php echo $peserta_lomba->getNamaPenggerakLingkungan() ?></td>
      <td><?php echo ($peserta_lomba->getTanggalPendaftaran() !== null && $peserta_lomba->getTanggalPendaftaran() !== '') ? format_date($peserta_lomba->getTanggalPendaftaran(), "f") : '' ?></td>
      <td><?php echo $peserta_lomba->getProgramKerja() ?></td>
      <td><?php echo $peserta_lomba->getCatatan() ?></td>
      <td><?php echo get_partial('opsi', array('type' => 'list', 'peserta_lomba' => $peserta_lomba)) ?></td>
  