<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:54
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'pesertaLomba/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
</ul>
