<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:53
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Form Pengisian Data Peserta', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('pesertaLomba/edit_header', array('peserta_lomba' => $peserta_lomba)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('pesertaLomba/edit_messages', array('peserta_lomba' => $peserta_lomba, 'labels' => $labels)) ?>
<?php include_partial('pesertaLomba/edit_form', array('peserta_lomba' => $peserta_lomba, 'labels' => $labels)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('pesertaLomba/edit_footer', array('peserta_lomba' => $peserta_lomba)) ?>
</div>

</div>
