<?php
// auto-generated by sfPropelAdmin
// date: 2018/03/21 16:05:53
?>
<?php

/**
 * autoPesertaLomba actions.
 *
 * @package    ##PROJECT_NAME##
 * @subpackage autoPesertaLomba
 * @author     Fabien Potencier <fabien.potencier@symfony-project.com>
 * @version    SVN: $Id: actions.class.php 9855 2008-06-25 11:26:01Z FabianLange $
 */
class autoPesertaLombaActions extends sfActions
{
  public function executeIndex()
  {
    return $this->forward('pesertaLomba', 'list');
  }

  public function executeList()
  {
    $this->processSort();

    $this->processFilters();


    // pager
    $this->pager = new sfPropelPager('PesertaLomba', 20);
    $c = new Criteria();
    $this->addSortCriteria($c);
    $this->addFiltersCriteria($c);
    $this->pager->setCriteria($c);
    $this->pager->setPage($this->getRequestParameter('page', $this->getUser()->getAttribute('page', 1, 'sf_admin/peserta_lomba')));
    $this->pager->init();
    // save page
    if ($this->getRequestParameter('page')) {
        $this->getUser()->setAttribute('page', $this->getRequestParameter('page'), 'sf_admin/peserta_lomba');
    }
  }

  public function executeCreate()
  {
    return $this->forward('pesertaLomba', 'edit');
  }

  public function executeSave()
  {
    return $this->forward('pesertaLomba', 'edit');
  }

  public function executeEdit()
  {
    $this->peserta_lomba = $this->getPesertaLombaOrCreate();

    if ($this->getRequest()->getMethod() == sfRequest::POST)
    {
      $this->updatePesertaLombaFromRequest();

      $this->savePesertaLomba($this->peserta_lomba);

      $this->setFlash('notice', 'Your modifications have been saved');

      if ($this->getRequestParameter('save_and_add'))
      {
        return $this->redirect('pesertaLomba/create');
      }
      else if ($this->getRequestParameter('save_and_list'))
      {
        return $this->redirect('pesertaLomba/list');
      }
      else
      {
        return $this->redirect('pesertaLomba/edit?id='.$this->peserta_lomba->getId());
      }
    }
    else
    {
      $this->labels = $this->getLabels();
    }
  }

  public function executeDelete()
  {
    $this->peserta_lomba = PesertaLombaPeer::retrieveByPk($this->getRequestParameter('id'));
    $this->forward404Unless($this->peserta_lomba);

    try
    {
      $this->deletePesertaLomba($this->peserta_lomba);
    }
    catch (PropelException $e)
    {
      $this->getRequest()->setError('delete', 'Could not delete the selected Peserta lomba. Make sure it does not have any associated items.');
      return $this->forward('pesertaLomba', 'list');
    }

    return $this->redirect('pesertaLomba/list');
  }

  public function handleErrorEdit()
  {
    $this->preExecute();
    $this->peserta_lomba = $this->getPesertaLombaOrCreate();
    $this->updatePesertaLombaFromRequest();

    $this->labels = $this->getLabels();

    return sfView::SUCCESS;
  }

  protected function savePesertaLomba($peserta_lomba)
  {
    $peserta_lomba->save();

  }

  protected function deletePesertaLomba($peserta_lomba)
  {
    $peserta_lomba->delete();
  }

  protected function updatePesertaLombaFromRequest()
  {
    $peserta_lomba = $this->getRequestParameter('peserta_lomba');

    if (isset($peserta_lomba['id_peserta']))
    {
    $this->peserta_lomba->setIdPeserta($peserta_lomba['id_peserta'] ? $peserta_lomba['id_peserta'] : null);
    }
    if (isset($peserta_lomba['id_lomba']))
    {
    $this->peserta_lomba->setIdLomba($peserta_lomba['id_lomba'] ? $peserta_lomba['id_lomba'] : null);
    }
    if (isset($peserta_lomba['tahun']))
    {
      $this->peserta_lomba->setTahun($peserta_lomba['tahun']);
    }
    if (isset($peserta_lomba['nama_tim']))
    {
      $this->peserta_lomba->setNamaTim($peserta_lomba['nama_tim']);
    }
    if (isset($peserta_lomba['nama_penggerak_lingkungan']))
    {
      $this->peserta_lomba->setNamaPenggerakLingkungan($peserta_lomba['nama_penggerak_lingkungan']);
    }
    if (isset($peserta_lomba['tanggal_pendaftaran']))
    {
      if ($peserta_lomba['tanggal_pendaftaran'])
      {
        try
        {
          $dateFormat = new sfDateFormat($this->getUser()->getCulture());
                              if (!is_array($peserta_lomba['tanggal_pendaftaran']))
          {
            $value = $dateFormat->format($peserta_lomba['tanggal_pendaftaran'], 'I', $dateFormat->getInputPattern('g'));
          }
          else
          {
            $value_array = $peserta_lomba['tanggal_pendaftaran'];
            $value = $value_array['year'].'-'.$value_array['month'].'-'.$value_array['day'].(isset($value_array['hour']) ? ' '.$value_array['hour'].':'.$value_array['minute'].(isset($value_array['second']) ? ':'.$value_array['second'] : '') : '');
          }
          $this->peserta_lomba->setTanggalPendaftaran($value);
        }
        catch (sfException $e)
        {
          // not a date
        }
      }
      else
      {
        $this->peserta_lomba->setTanggalPendaftaran(null);
      }
    }
    if (isset($peserta_lomba['program_kerja']))
    {
      $this->peserta_lomba->setProgramKerja($peserta_lomba['program_kerja']);
    }
    if (isset($peserta_lomba['catatan']))
    {
      $this->peserta_lomba->setCatatan($peserta_lomba['catatan']);
    }
  }

  protected function getPesertaLombaOrCreate($id = 'id')
  {
    if (!$this->getRequestParameter($id))
    {
      $peserta_lomba = new PesertaLomba();
    }
    else
    {
      $peserta_lomba = PesertaLombaPeer::retrieveByPk($this->getRequestParameter($id));

      $this->forward404Unless($peserta_lomba);
    }

    return $peserta_lomba;
  }

  protected function processFilters()
  {
  }

  protected function processSort()
  {
    if ($this->getRequestParameter('sort'))
    {
      $this->getUser()->setAttribute('sort', $this->getRequestParameter('sort'), 'sf_admin/peserta_lomba/sort');
      $this->getUser()->setAttribute('type', $this->getRequestParameter('type', 'asc'), 'sf_admin/peserta_lomba/sort');
    }

    if (!$this->getUser()->getAttribute('sort', null, 'sf_admin/peserta_lomba/sort'))
    {
    }
  }

  protected function addFiltersCriteria($c)
  {
  }

  protected function addSortCriteria($c)
  {
    if ($sort_column = $this->getUser()->getAttribute('sort', null, 'sf_admin/peserta_lomba/sort'))
    {
      $sort_column = PesertaLombaPeer::translateFieldName($sort_column, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_COLNAME);
      if ($this->getUser()->getAttribute('type', null, 'sf_admin/peserta_lomba/sort') == 'asc')
      {
        $c->addAscendingOrderByColumn($sort_column);
      }
      else
      {
        $c->addDescendingOrderByColumn($sort_column);
      }
    }
  }

  protected function getLabels()
  {
    return array(
      'peserta_lomba{id_peserta}' => 'Asal:',
      'peserta_lomba{id_lomba}' => 'Kompetisi:',
      'peserta_lomba{tahun}' => 'Tahun:',
      'peserta_lomba{nama_tim}' => 'Nama Tim:',
      'peserta_lomba{nama_penggerak_lingkungan}' => 'Penggerak Lingkungan:',
      'peserta_lomba{tanggal_pendaftaran}' => 'Tanggal Pendaftaran:',
      'peserta_lomba{program_kerja}' => 'Program Kerja:',
      'peserta_lomba{catatan}' => 'Catatan:',
    );
  }
}
