<?php
// auto-generated by sfPropelAdmin
// date: 2014/10/28 07:35:46
?>

<?php 
$fileDir = '/uploads/Lomba/Tim/'.$data_lomba->getFilenameBaru().'.png';
?>

<?php echo link_to(image_tag($fileDir, array('style'=>'max-height:150px')), 'dataLomba/downloadRequest?id='.$data_lomba->getId())?>

